kind = "web"
previewPath = "/"
title = "JamilaPharm"
version = "1.0.0"
id = "artifacts/jamilapharm"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22108

[services.development]
run = "pnpm --filter @workspace/jamilapharm run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/jamilapharm", "run", "build" ]
publicDir = "artifacts/jamilapharm/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22108"
BASE_PATH = "/"
